### ISSUE TITLE
ask for help on solution and trajectory reference

### ISSUE THREAD

**Issue by Charvelau** [mayataka/autogenu-jupyter#11]
Dear Katayama-san,
I want to ask for you help on two issues.
**_First,_** How can I get the first state of the solution from your solve and then give it to my real dynamic system, i.e., in order to implement your algorithm to a real system(can be simulation based on physics engine) rather than just in simulator?
**_Second,_** Is it possible to define a time variant boundary constraint or reference trajectory based stage cost? Say, I need the control input to be close to a predefined trajectory? How can I pass these parameters to the constraint or stage cost?

If you have any clue or thought, please let me know, it will be really appreciated.
Thank you very much. 
Qingwei Liu
AIST, Tsukuba

**Comment by mayataka** [comment]
Hi. 
The first problem may depend on what interface you will use. 
If a physics engine can call C++ function, you may be able to get the optimal control input in principle. 
Some interface needs that you have to add a function to convert a C++ raw array to another type of the interface. Then you have to write such function in ```ContinuationGMRES``` class, ```MultipleShootingGMRES``` class, or ```MultipleShootingGMRESWithSaturation``` class by yourself.

The second problem is shown in ```hexacopter.ipynb```. 
In the example, I define time-variant reference state trajectory and design the cost function that weights the quadratic term of the error between the system's state trajectory and the reference state trajectory. The example may help your understanding. 
Another way to consider the time-variant reference trajectory is to impose a constraint. In the code generation, you can define the equality constraints ```Cxu```. If you define state trajectory ```x_ref``` and  define the constraint e.g., as ```Cxu = [x[i] - x_ref[i] for i in range(dimx)]``` , then it may work well. But I don't use the latter way, so I'm not confident whether it works well or not.

**Comment by Charvelau** [comment]
Hi thank you very much for your reply. I will try it later and let you know.

Best regards
Qingwei Liu
