### ISSUE TITLE
Suggestion: Inequality constraint handling method

### ISSUE THREAD

**Issue by asadjadi** [mayataka/autogenu-jupyter#13]
Dear all,

I would like to thank you very much for your useful repository. I was working with the C/GMRES method for my PhD with the Maple interface and I enjoyed a lot.

I would like to introduce you the transformation method which can increase the capability of the CGMRES in handling the inequality constraints in a robust way. Please find the following link for your information. I would be very happy to have these methods also in your tool.

Fischer-Burmeister method (page 5: Semi-smooth Transformation):
https://www.sciencedirect.com/science/article/pii/S2405896315025926

Thesis (inequality constraints):
https://deepblue.lib.umich.edu/bitstream/handle/2027.42/120832/huxuli_1.pdf?sequence=1&isAllowed=y

Smoothed Fischer-Burmeister Method:
https://arxiv.org/pdf/1807.03214.pdf

My PhD thesis:
http://orbilu.uni.lu/handle/10993/36164

Thank you very much for your kind consideration in advance. Keep up the good work.
Best regards,
Amin

**Comment by mayataka** [comment]
Thank you so much for introducing very interesting researches.
It seems really useful and I consider incorporating your method into this tool.

**Comment by asadjadi** [comment]
Thank you very much Mayataka, for your kind response. If you believe that I can be helpful, please feel free to contact me. I would be more than happy to contribute in this project. Wish you all the best.

**Comment by mayataka** [comment]
I have added a .ipynb example of obstacle avoidance of a mobile robot as an example of the semi-smooth Fischer-Burmeister method. In that example, I verified that it works well for both control-variable inequality constraints and state-variable inequality constraints. 
Thank you so much for the nice suggestion.

If there is something wrong with the example, or if you can provide me further suggestions, feel free to reopen this issue.

**Comment by asadjadi** [comment]
Thank you very much for your kind consideration. It looks very good. Wish you all the best.
