### ISSUE TITLE
the prediction horizon and the period for implementation

### ISSUE THREAD

**Issue by 18120251** [mayataka/autogenu-jupyter#22]
Hello. The two parameters of prediction horizon and period for implementation are important for MPC. I know that the prediction horizon is variable “T_f” in the code, but I do not see the parameter of period for implementation. In the c ++ source code, it seems that the step of the period for implementation is 1, can this parameter be configured separately? Unfortunately my C ++ foundation is not very good, I wish that you can help me. 
Thanks!

**Comment by 18120251** [comment]
According to my understanding, the function “solveLinerProblem” in the file “multiple_shooting_cmgres.cpp” is the function to solve the optimal control input U, but because I am not familiar with C ++, its parameters and calling methods are somewhat unclear to me, even if I debug line by line, I didn't get how the array "control_input_and_constraints_seq_ " was calculated. Obviously this parameter is related to the optimal control input U, but I see that the value stored in this array "control_input_and_constraints_seq_ " is repeated cyclically with the size of "dim_control_input + dim_constraints". I think if the prediction time domain is " T_f ", and the prediction step size is" N ", then the data stored in this array should be N sets of data, respectively representing the optimal control amount under each prediction step size, and should not be repeated cyclically. I wish that you can help me. Thanks!

**Comment by mayataka** [comment]
I'm sorry, I cannot get what you mean by "period for implementation". 
"control_input_and_constraints_seq_" is the array of the future optimal control input and the Lagrange multipliers with respect to the equality constraints. 
I do not use 2D array (array of array) but instead I represent them by 1D array. This is the reason why the type of control_input_and_constraints_seq_ is double* (not double**) and its size is N * (dim_control_input + dim_constraints).

**Comment by 18120251** [comment]
> I'm sorry, I cannot get what you mean by "period for implementation".
> "control_input_and_constraints_seq_" is the array of the future optimal control input and the Lagrange multipliers with respect to the equality constraints.
> I do not use 2D array (array of array) but instead I represent them by 1D array. This is the reason why the type of control_input_and_constraints_seq_ is double* (not double**) and its size is N * (dim_control_input + dim_constraints).



> I'm sorry, I cannot get what you mean by "period for implementation".
> "control_input_and_constraints_seq_" is the array of the future optimal control input and the Lagrange multipliers with respect to the equality constraints.
> I do not use 2D array (array of array) but instead I represent them by 1D array. This is the reason why the type of control_input_and_constraints_seq_ is double* (not double**) and its size is N * (dim_control_input + dim_constraints).

Thank you for your quick reply!

If the variable "N" is seen as the prediction horizon, the optimal control solution should be an array of optimal control inputs and Lagrange multipliers, having a size of N * (dim_control_input + dim_constraintsd), which should be applied separately N times after time t (that is, the duration of T_f). But according to the content of your reply, it seems that there is only an array with a size of 1 * (dim_control_input + dim_constraintsd), which I don't quite understand.

Regarding what I mean by "period for implementation", assuming that it is seen as constant "M" (0 <M <= N), it means the optimal control input and Lagrange multiplier within these N steps In the array, select the top M pieces of data (that is, an array having a size of M * (dim_control_input + dim_constraintsd)) as the control input and the Lagrange multiplier applied during numerical simulation. Therefore, at each sampling time t, the numerical simulation within the time interval [t: t + M * sampling_time] should be completed (Note: sampling_time = T_f / N is assumed here). After the numerical simulation is completed, the optimal control input for the next stage is recalculated (the sampling time at this time is t + M * sampling_time). Repeat this cycle.

According to the content of the code, I think your "period for implementation" may be 1, that is, the optimal control solution will be re-executed every sampling period of the numerical simulation, and the optimal control input obtained each time can only be applied to the current Period, that is to say, it seems that the optimal control input in (t: t+N*sampling_time] (Note: sampling_time = T_f / N is assumed here) is not available.

Hope you can help me, thank you!

**Comment by mayataka** [comment]
> First, sampling_time = T_f / N is assumed here. If the variable "N" is seen as the prediction horizon, the optimal control solution should be an array of optimal control inputs and Lagrange multipliers, having a size of N * (dim_control_input + dim_constraintsd), which should be applied at time t, t+sampling_time , t+2sampling_time ... t+Nsampling_time (that is [t: t + N* sampling_time], in the duration of T_f). But according to the content of your reply, it seems that there is only an array with a size of 1 * (dim_control_input + dim_constraintsd) applied at time t, which I don't quite understand.

In the C/GMRES method, basically the first control input, i.e., `1*(dim_control_input+dim_constraints)` is applied to the system in each sampling time.  That is, `2*(dim_control_input+dim_constraints)`... `N*(dim_control_input+dim_constraints)` are never applied to the actual system. However, optimal `2*(dim_control_input+dim_constraints)`... `N*(dim_control_input+dim_constraints)` are also calculated at each sampling time to "track" the optimal solution according to the change of the actual system's state at each sampling time.

> Regarding what I mean by "period for implementation", assuming that it is seen as constant "M" (0 <M <= N), it means the optimal control input and Lagrange multiplier within these N steps In the array, select the top M pieces of data (that is, an array having a size of M * (dim_control_input + dim_constraintsd)) as the control input and the Lagrange multiplier applied during numerical simulation. Therefore, at each sampling time t, the numerical simulation within the time interval [t: t + M * sampling_time] should be completed. After the numerical simulation is completed, the optimal control input for the next stage is recalculated (the sampling time at this time is t + M * sampling_time). Repeat this cycle.
> According to the content of the code, I think your "period for implementation" may be 1, that is, the optimal control solution will be re-executed every sampling period of the numerical simulation, and the optimal control input obtained each time can only be applied to the current Period, that is to say, it seems that the optimal control input in (t: t+N*sampling_time] is not available.

In the context of your "period for implementation", M is always 1. As stated before, the optimal control inputs at 2-N are never used. This is the principle of the C/GMRES method.

**Comment by 18120251** [comment]
> > First, sampling_time = T_f / N is assumed here. If the variable "N" is seen as the prediction horizon, the optimal control solution should be an array of optimal control inputs and Lagrange multipliers, having a size of N * (dim_control_input + dim_constraintsd), which should be applied at time t, t+sampling_time , t+2sampling_time ... t+Nsampling_time (that is [t: t + N* sampling_time], in the duration of T_f). But according to the content of your reply, it seems that there is only an array with a size of 1 * (dim_control_input + dim_constraintsd) applied at time t, which I don't quite understand.
> 
> In the C/GMRES method, basically the first control input, i.e., `1*(dim_control_input+dim_constraints)` is applied to the system in each sampling time. That is, `2*(dim_control_input+dim_constraints)`... `N*(dim_control_input+dim_constraints)` are never applied to the actual system. However, optimal `2*(dim_control_input+dim_constraints)`... `N*(dim_control_input+dim_constraints)` are also calculated at each sampling time to "track" the optimal solution according to the change of the actual system's state at each sampling time.
> 
Thank you for your reply！

Another problem is that you say "optimal 2 * (dim_control_input + dim_constraints) ... N * (dim_control_input + dim_constraints) are also calculated at each sampling time to" track "the optimal solution according to the change of the actual system's state at each sampling time. ".However, according to my code debugging,  values in control_input_and_constraints_seq_ are repeated cyclically in cycles of (dim_control_input + dim_constraintsd),
(for example, control_input_and_constraints_seq_[0] = control_input_and_constraints_seq_[dim_control_input + dim_constraintsd] = control_input_and_constraints_seq_[2dim_control_input + 2dim_constraintsd] in function getControlInput in file multiple_shooting_cmgres.cpp) ,
which I don't quite understand.
> > Regarding what I mean by "period for implementation", assuming that it is seen as constant "M" (0 <M <= N), it means the optimal control input and Lagrange multiplier within these N steps In the array, select the top M pieces of data (that is, an array having a size of M * (dim_control_input + dim_constraintsd)) as the control input and the Lagrange multiplier applied during numerical simulation. Therefore, at each sampling time t, the numerical simulation within the time interval [t: t + M * sampling_time] should be completed. After the numerical simulation is completed, the optimal control input for the next stage is recalculated (the sampling time at this time is t + M * sampling_time). Repeat this cycle.
> > According to the content of the code, I think your "period for implementation" may be 1, that is, the optimal control solution will be re-executed every sampling period of the numerical simulation, and the optimal control input obtained each time can only be applied to the current Period, that is to say, it seems that the optimal control input in (t: t+N*sampling_time] is not available.
> 
> In the context of your "period for implementation", M is always 1. As stated before, the optimal control inputs at 2-N are never used. This is the principle of the C/GMRES method.

**Comment by mayataka** [comment]
> Another problem is that you say "optimal 2 * (dim_control_input + dim_constraints) ... N * (dim_control_input + dim_constraints) are also calculated at each sampling time to" track "the optimal solution according to the change of the actual system's state at each sampling time. ".However, according to my code debugging, values in control_input_and_constraints_seq_ are repeated cyclically in cycles of (dim_control_input + dim_constraintsd),
(for example, control_input_and_constraints_seq_[0] = control_input_and_constraints_seq_[dim_control_input + dim_constraintsd] = control_input_and_constraints_seq_[2dim_control_input + 2dim_constraintsd] in function getControlInput in file multiple_shooting_cmgres.cpp) ,
which I don't quite understand.

When you check the values of control_input_and_constraints_seq_? 
At the beginning of the numerical simulation, the length of the horizon is set by zero and all control_input_and_constraints_seq_[i*dim_control_input + i*dim_constraintsd] are the same. 
This is to initialize the solution very fast by solving the optimal control problem whose length of the horizon is zero.
At time goes by, the length horizon increases, and control_input_and_constraints_seq_[i*dim_control_input + i*dim_constraintsd] may have different values.

**Comment by 18120251** [comment]
> > Another problem is that you say "optimal 2 * (dim_control_input + dim_constraints) ... N * (dim_control_input + dim_constraints) are also calculated at each sampling time to" track "the optimal solution according to the change of the actual system's state at each sampling time. ".However, according to my code debugging, values in control_input_and_constraints_seq_ are repeated cyclically in cycles of (dim_control_input + dim_constraintsd),
> > (for example, control_input_and_constraints_seq_[0] = control_input_and_constraints_seq_[dim_control_input + dim_constraintsd] = control_input_and_constraints_seq_[2dim_control_input + 2dim_constraintsd] in function getControlInput in file multiple_shooting_cmgres.cpp) ,
> > which I don't quite understand.
> 
> When you check the values of control_input_and_constraints_seq_?
> At the beginning of the numerical simulation, the length of the horizon is set by zero and all control_input_and_constraints_seq_[i_dim_control_input + i_dim_constraintsd] are the same.
> This is to initialize the solution very fast by solving the optimal control problem whose length of the horizon is zero.
> At time goes by, the length horizon increases, and control_input_and_constraints_seq_[i_dim_control_input + i_dim_constraintsd] may have different values.

Thanks for your guidance, I have found the problem. I set the alpha parameter so small that I found the phenomenon of cyclic repetition in the first few cycles of simulation.
