### ISSUE TITLE
inequality constraint at specific time t

### ISSUE THREAD

**Issue by bjoern-zobrist** [mayataka/autogenu-jupyter#24]
Hello. Is it possible to have an inequality constraint only at a specific time t, for example after 4 seconds of the simulation?

I'm trying to use autogenu to find the fastest way from point A to B with a certain maximum and minimum acceleration with the constraint that at a specific time the velocity must be lower than v_max.

Thanks!

**Comment by mayataka** [comment]
I'm sorry that I did not notice this issue.
This requires hard coding to modify generated source files.
