### ISSUE TITLE
How to build and launch autogenu-jupyter example?

### ISSUE THREAD

**Issue by Geonhee-LEE** [mayataka/autogenu-jupyter#27]
Hi, @mayataka.
Thanks for your contribution.
I want to run your source, therefore I wonder let me know how to build and launch autogenu-jupyter example.

**Comment by mayataka** [comment]
Hi @Geonhee-LEE,
All procedures, ie.g., code generations, compilations, and simulations are run through Jupyter notebook or Jpyter lab.
First please launch Jupyter notebook or Jupyter lab.
Then open an `.ipynb` example file (e.g., `cartpole.ipynb`).
By running the cells of the notebook, the above procedure will be executed.
